### ISSUE TITLE
Add PDF and postscript files to preconfigured sets of allowable files

### ISSUE THREAD

**Issue by jeffwidman** [jeffwidman/flask-uploads#11]
Originally reported by: **Patrick Schmid (BitBucket: [prschmid](http://bitbucket.org/prschmid), GitHub: [prschmid](http://github.com/prschmid))**

----------------------------------------

----------------------------------------
- Bitbucket: https://bitbucket.org/leafstorm/flask-uploads/issue/11

**Comment by jeffwidman** [comment]
I'm okay with adding PDFs, not sure about postscript files. 

Which specific file extensions would you add @prschmid for postscript extensions?

**Comment by prschmid** [comment]
I'd just add ``.ps``, but I'd be fine with just ``.pdf`` as well since postscript files are less common. I'll leave that up to you.

This is note part of this particular issue (and I'll happily create another issue), but any thoughts on providing hooks to actually inspect the files to ensure that the extension matches the contents? Of course, you can (validly) argue that this is outside the scope of flask-uploads. =)

Thanks!

**Comment by jeffwidman** [comment]
@prschmid yeah, if you don't mind, can you create another issue about adding hooks for file inspection? 

At first glance, this sounds interesting and within the scope of Flask-Uploads if all we're doing here is exposing some additional hooks. 

I need to understand more of what you'd like the API to look like (a few lines of pseudocode would be useful). Also include a brief explanation of what problem(s) this would actually solve for you, just to make sure there isn't a better way to solve what you're trying to accomplish.

**Comment by prschmid** [comment]
Thanks! Just added the file validation suggestion as issue as #18 . Let me know if you need any more clarification/want me to submit a pull request.
